const professions = [
  {
    name: "Policjant",
    salaryRange: [10000, 15000],
    image: "policeman.jpg",
    description: "Stróż prawa dbający o bezpieczeństwo na ulicach.",
    water: 3,
    food: 3000,
    bonusChance: 20,
    otherSkills: ["<span>📈</span> Szansa na większy zarobek"],
    higherSalary: true,
  },
  {
    name: "YouTuber",
    salaryRange: [1000, 150000],
    image: "youtuber.jpg",
    description: "Nagrywa i montuje filmy. Lubi dostawać suby i łapki w górę.",
    water: 3,
    food: 2000,
    bonusChance: 30,
    otherSkills: ["<span>🖤</span> Większa utrata zdrowia"],
  },
  {
    name: "Strażak",
    salaryRange: [9000, 14000],
    image: "fireman.jpg",
    description: "Ratownik gaszący pożary i ratujący ludzi.",
    water: 4,
    food: 3500,
    bonusChance: 10,
    otherSkills: ["<span>🔥</span> większa odporność na ogień"],
  },
  {
    name: "Lekarz",
    salaryRange: [18000, 22000],
    image: "doctor.jpg",
    description: "Specjalista zajmujący się leczeniem pacjentów.",
    water: 2,
    food: 3500,
    bonusChance: 5,
    otherSkills: ["<span>❤️</span> +5% do regeneracji zdrowia"],
  },
  {
    name: "Nauczyciel",
    salaryRange: [7000, 10000],
    image: "teacher.jpg",
    description: "Przekazuje wiedzę kolejnym pokoleniom.",
    water: 2,
    food: 2000,
    bonusChance: 30,
    otherSkills: ["<span>🖤</span> Większa utrata zdrowia"],
  },
  {
    name: "Mechanik",
    salaryRange: [8000, 12000],
    image: "mechanic.jpg",
    description: "Naprawia i konserwuje pojazdy.",
    water: 2,
    food: 2800,
    bonusChance: 5,
    otherSkills: ["<span>🚙</span> -10% do zakupu samochodów"],
  },
  {
    name: "Inżynier",
    salaryRange: [13000, 19000],
    image: "engineer.jpg",
    description: "Projektuje i buduje nowoczesne technologie.",
    water: 3,
    food: 3200,
    bonusChance: 25,
    otherSkills: ["<span>📈</span> Szansa na większy zarobek"],
  },
  {
    name: "Rolnik",
    salaryRange: [6000, 9000],
    image: "farmer.jpg",
    description: "Uprawia ziemię i hoduje zwierzęta.",
    water: 5,
    food: 4000,
    bonusChance: 10,
    otherSkills: [`<span>🥦</span> -25% do cen żywności`],
  },
  {
    name: "Kierowca ciężarówki",
    salaryRange: [9000, 13000],
    image: "truck-driver.jpg",
    description: "Transportuje towary na duże odległości.",
    water: 2,
    food: 3500,
    bonusChance: 20,
    otherSkills: ["<span>🚙</span> -5% do zakupu samochodów"],
  },
  {
    name: "Programista",
    salaryRange: [14000, 20000],
    image: "programmer.jpg",
    description: "Pisze i rozwija oprogramowanie.",
    water: 1,
    food: 1800,
    bonusChance: 35,
    otherSkills: ["<span>🖤</span> Większa utrata zdrowia"],
  },
  {
    name: "Kucharz",
    salaryRange: [7000, 11000],
    image: "cook.jpg",
    description: "Przygotowuje pyszne posiłki dla klientów.",
    water: 3,
    food: 2800,
    bonusChance: 40,
    otherSkills: ["<span>🥦</span> -20% do cen żywności"],
  },
];
